ARG RUBY_VERSION=3.3.1
FROM docker.io/library/ruby:$RUBY_VERSION-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential curl git libyaml-dev pkg-config \
      libjemalloc2 libvips sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install correct Bundler version (must match BUNDLED WITH in Gemfile.lock)
RUN gem install bundler -v 2.7.1 && \
    gem install foreman

EXPOSE 3000

CMD ["bin/setup"]
